#ifndef _RESOURCEMANAGER_H_
#define _RESOURCEMANAGER_H_

class ResourceManager
{
public:
	ResourceManager();
	~ResourceManager();
	void InitialisePlayingScreen();

	enum Object
	{
		PLAYER_SPRITE,
		ENEMY_FRIGATE_SPRITE,
		ENEMY_CRUISER_SPRITE,
		ENEMY_BATTLESHIP_SPRITE,
		P_BULLET_SPRITE,
		E_BULLET_SPRITE,
		POWERUP_UPGRADE_LEVEL1_SPRITE,
		POWERUP_UPGRADE_LEVEL2_SPRITE,
		POWERUP_UPGRADE_LEVEL3_SPRITE,
		POWERUP_LIFE_SPRITE,
		EXPLOSION_SPRITE,
		PLAYER_LIVES_SPRITE,
		BACKGROUND_LEVEL1_SPRITE,
		BACKGROUND_LEVEL2_SPRITE,
		BACKGROUND_LEVEL3_SPRITE,
		TRANSPARENT_BACKGROUND_SPRITE,
		MAIN_MENU_BACKGROUND,
		GAME_TITLE_TEXT,
		START_GAME_TEXT,
		OPTIONS_TEXT,
		HIGHSCORES_TEXT,
		HELP_TEXT,
		QUIT_TEXT,
		SPLASHSCREEN_1,
		SPLASHSCREEN_2

	};


private:

	int screenWidth;
	int screenHeight;
	const char* title[];
};

#endif // !_RESOURCEMANAGER_H_